# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files in the extra_config_files directory to override
# the content from this file

# Extra configuration directory where the config files overriding this file
# should be.
extra_config_files: /etc/wazo-phoned/conf.d/

log_filename: /var/log/wazo-phoned.log
pid_filename: /var/run/wazo-phoned/wazo-phoned.pid
foreground: False
debug: False

auth:
  host: localhost
  port: 9497
  key_file: /var/lib/wazo-auth-keys/wazo-phoned-key.yml
  verify_certificate: /usr/share/xivo-certs/server.crt  # True, False or CA Bundle

dird:
  host: localhost
  port: 9489
  verify_certificate: /usr/share/xivo-certs/server.crt  # True, False or CA Bundle

# REST API server
rest_api:

  http:
    enabled: True
    listen: 0.0.0.0
    port: 9498

  https:
    enabled: True
    listen: 0.0.0.0
    port: 9499

    certificate: /usr/share/xivo-certs/server.crt
    private_key: /usr/share/xivo-certs/server.key

  # Authorizing subnets
  # authorized_subnets:
  #   - '192.168.0.0/16'

  # CORS configuration. See Flask-CORS documentation for other values.
  cors:
    enabled: True

enabled_plugins:
  aastra: True
  api: True
  status: True
