version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 phoned:9499 dird:9489"
  phoned:
    image: xivo-dird-phoned-test
    ports:
      - "9498"
      - "9499"
    volumes:
      - "./etc/xivo-dird-phoned:/etc/xivo-dird-phoned"
      - "../../..:/usr/src/xivo-dird-phoned"
      - "./ssl:/etc/ssl"
      - "./auth_keys:/tmp/auth_keys"
  dird:
    image: p0bailey/docker-flask
    expose:
      - "9489"
    volumes:
      - "./dird_data:/tmp"
      - "./ssl:/etc/ssl"
    command: "python /tmp/mock-xivo-dird.py 9489"
