version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/xivo-dird-phoned/conf.d/config.http_and_https_enable_false.yml:/etc/xivo-dird-phoned/conf.d/config.http_and_https_enable_false.yml"
