version: '3.7'
services:
  sync:
    image: wazopbx/wait
    environment:
      TIMEOUT: ${INTEGRATION_TEST_TIMEOUT}

  phoned:
    image: wazo-phoned-test
    ports:
      - "9498"
      - "9499"
    volumes:
      - "../..:/usr/src/wazo-phoned"
      - "./ssl:/etc/ssl"
      - "./auth_keys:/tmp/auth_keys"
      - "./etc/wazo-phoned/conf.d/50-auth.yml:/etc/wazo-phoned/conf.d/50-auth.yml"
      - "./etc/wazo-phoned/conf.d/50-dird.yml:/etc/wazo-phoned/conf.d/50-dird.yml"
      - "./etc/wazo-phoned/conf.d/50-bus.yml:/etc/wazo-phoned/conf.d/50-bus.yml"
      - "./etc/wazo-phoned/conf.d/50-rest-api.yml:/etc/wazo-phoned/conf.d/50-rest-api.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python3.7/site-packages/xivo"
    environment:
        XIVO_UUID: 08c56466-8f29-45c7-9856-92bf1ba89b93

  dird:
    image: p0bailey/docker-flask
    expose:
      - "9489"
    volumes:
      - "./dird_data:/tmp"
      - "./ssl:/etc/ssl"
    command: "python /tmp/mock-wazo-dird.py 9489"

  auth:
    image: "wazopbx/wazo-auth-mock"
    ports:
      - "9497"
    volumes:
      - "./ssl:/usr/local/share/ssl/auth"

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672
    volumes:
      - type: tmpfs
        target: /var/lib/rabbitmq

  amid:
    image: p0bailey/docker-flask
    ports:
      - 9491
    volumes:
      - ./amid_data:/usr/local/share/wazo-amid
      - ./ssl:/usr/local/share/ssl
    command: python /usr/local/share/wazo-amid/mock-wazo-amid.py 9491
