version: '3'
services:
  sync:
    depends_on:
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 phoned:9499 dird:9489"

  phoned:
    volumes:
      - "./etc/xivo-dird-phoned/conf.d/config.no_auth_server.yml:/etc/xivo-dird-phoned/conf.d/config.no_auth_server.yml"
