version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9499 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/xivo-dird-phoned/conf.d/20-http-disabled.yml:/etc/xivo-dird-phoned/conf.d/20-http-disabled.yml"
