version: '3.7'
services:
  sync:
    depends_on:
      - rabbitmq
      - amid
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "rabbitmq:5672 amid:9491 phoned:9498 phoned:9499 dird:9489 auth:9497"
