version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/wazo-phoned/conf.d/20-https-disabled.yml:/etc/wazo-phoned/conf.d/20-https-disabled.yml"
