version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/xivo-dird-phoned/conf.d/config.no_ssl_private_key.yml:/etc/xivo-dird-phoned/conf.d/config.no_ssl_private_key.yml"
