version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/wazo-dird-phoned/conf.d/20-no-auth-key.yml:/etc/wazo-dird-phoned/conf.d/20-no-auth-key.yml"
