version: '3'
services:
  sync:
    depends_on:
      - auth
      - dird
      - phoned
    environment:
      TARGETS: "phoned:9498 phoned:9499 dird:9489 auth:9497"

  phoned:
    volumes:
      - "./etc/xivo-dird-phoned/conf.d/config.default_config.yml:/etc/xivo-dird-phoned/conf.d/config.default_config.yml"
